Repository the3eyes/neat, pull requests merged in 2019-07, with the labels that each got.

#8 Added badges using travis and other services
  .coveralls.yml
  .readthedocs.yml
  .travis.yml
  README.md
Labels: ci/cd

#12 Added experiments in the experiment folder
  .coveralls.yml
  .readthedocs.yml
  .travis.yml
  README.md
  experiments/__init__.py
  experiments/backprop_numpy/__init__.py
  experiments/backprop_numpy/activations.py
  experiments/backprop_numpy/examples/__init__.py
  experiments/backprop_numpy/examples/feedforward_sigmoid_sse_sgd.py
  experiments/backprop_numpy/losses.py
  experiments/backprop_numpy/models_sequential.py
  experiments/backprop_numpy/optimizers.py
  experiments/backprop_numpy/test_backprop_numpy.py
  experiments/tf2_mnist/mnist_example.py
  requirements.txt
  setup.py
Labels: please merge!

#15 Fixed Makefile, added install section
  Makefile
Labels: please merge!

#17 Update Makefile
  Makefile
Labels: please merge!

#24 Fixed badges and badge links
  .coveralls.yml
  README.md
Labels: please merge!

#20 Partially implemented Node, Connection, Genome and Species classes
  docs/system_design/classes.md
  neat/genes.py
  neat/genomes.py
  neat/species.py
  tests/test_genes.py
  tests/test_genomes.py
  tests/test_species.py
Labels: changes requested

#25 Elcid/docsfix and makefile fix
  Makefile
  README.md
Labels: please merge!

#26 removed branch specification from Coverage Badge
  README.md
Labels: please merge!
